name: hotel_ordering_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0      # â† use a valid version



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.9.2"     # add this line

flutter_icons:                         # add this block
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:                              # uncomment/add this section
    - assets/icon.png
